### ISSUE TITLE
Create a team command to easily update team changes

### ISSUE THREAD

**Issue by SenorKarlos** [TrainerDex/DiscordBot#36]
Title basically says it all, perhaps other parts of the !approve command could also get individual commands for updating users as well. Thanks!

**Comment by SenorKarlos** [comment]
I will add to this actually. When running the !approve just now to change the team, it didn't remove the former team role, only added to my current role set - so my in server color didn't change.

**Comment by TurnrDev** [comment]
Unsure as of yet if I'll want this to be a mod command or a unprivileged command. I feel like mod would make the most sense as to prevent abuse. 

####**Mod command**
#####_Pros_
- Managed by trusted members of the community
- User doesn't have to learn anything
##### _Cons_
- Users have to wait

####**Unprivileged**
#####_Pros_
- No wait required, as long as the user knows the command, they can update their team
#####_Cons_
- Users are able to freely reassign their team roles to spy in team chats, this would be undesirable in some guilds

**Comment by SenorKarlos** [comment]
Sorry I missed the reply, Mod and up only for sure. Thanks! :)

**Comment by TurnrDev** [comment]
Sweet! I'm working on a bug fix for [TrainerDex/PogoOCR](https://www.github.com/TrainerDex/PogoOCR) right now, as that's causing OCR to not work for several people. However, once that's done I'll start working on this as it won't be much work.

**Comment by TurnrDev** [comment]
Scrap the command, switch to a PokeNav style team OCR team check. 

Things we'll want to verify via the team check:
- Username matches what we have in file
- Find the team
- As a bonus, if stats found, update them. Since we're having to call Google Vision API anyway.

Steps: 
- Update PogoOCR to check for colours, you can find old working code in PokeOCR, your old project.
- Since this is the first time we're actively using the username from the OCR, use a tool to check if the username is a close enough match as OCR wasn't 100% accurate on that. @Azelphur, you used a tool for that to detect Pokémon and Gym typos in Monord, do you have any insights?

**Comment by TurnrDev** [comment]
Development on this has halted. It will still happen, just not yet. Sorry man.
